# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raw_current.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raw_current.proto',
  package='bio',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11raw_current.proto\x12\x03\x62io\"g\n\x07\x43urrent\x12\x14\n\x0c\x64igitisation\x18\x01 \x01(\x01\x12\x0e\n\x06offset\x18\x02 \x01(\x01\x12\r\n\x05range\x18\x03 \x01(\x01\x12\x15\n\rsampling_rate\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrents\x18\x05 \x03(\x01\x62\x06proto3')
)




_CURRENT = _descriptor.Descriptor(
  name='Current',
  full_name='bio.Current',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digitisation', full_name='bio.Current.digitisation', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='bio.Current.offset', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range', full_name='bio.Current.range', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sampling_rate', full_name='bio.Current.sampling_rate', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currents', full_name='bio.Current.currents', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['Current'] = _CURRENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Current = _reflection.GeneratedProtocolMessageType('Current', (_message.Message,), dict(
  DESCRIPTOR = _CURRENT,
  __module__ = 'raw_current_pb2'
  # @@protoc_insertion_point(class_scope:bio.Current)
  ))
_sym_db.RegisterMessage(Current)


# @@protoc_insertion_point(module_scope)
